export const sentences = [
  "I love walking in the park during autumn.",
  "She reads a book every night before bed.",
  "The cat is sleeping on the warm windowsill.",
  "We went to the beach and collected seashells.",
  "He enjoys cooking Italian dishes on weekends.",
  "The city lights look beautiful at night.",
  "I forgot my umbrella, and it started raining.",
  "They are planning a surprise birthday party.",
  "My brother plays the guitar very well.",
  "She bought a new dress for the party.",
  "I need to finish my homework before dinner.",
  "The train was late by ten minutes.",
  "He likes to jog every morning.",
  "We visited the museum last Saturday.",
  "The flowers in the garden are blooming.",
  "I watched a great movie yesterday.",
  "She smiled when she received the gift.",
  "He travels a lot for his job.",
  "The dog barked loudly at the stranger.",
  "I enjoy listening to classical music.",
  "The sky is clear and full of stars.",
  "He spilled coffee on his shirt this morning.",
  "We went hiking in the mountains last weekend.",
  "She painted a beautiful portrait.",
  "I baked a chocolate cake for my friend.",
  "The children are playing in the yard.",
  "He fixed the broken chair in the kitchen.",
  "We had a picnic by the lake.",
  "I forgot to lock the door.",
  "She danced gracefully on the stage.",
  "The baby laughed at the funny clown.",
  "He bought a new laptop for work.",
  "We are learning to speak French.",
  "I like swimming in the ocean.",
  "She adopted a cute little puppy.",
  "The sunset was breathtaking yesterday.",
  "He enjoys reading science fiction novels.",
  "We had dinner at a fancy restaurant.",
  "I need to clean my room today.",
  "She wore a red hat to the party.",
  "The bus was very crowded this morning.",
  "He plays chess with his friends every week.",
  "I drank a cup of tea before bedtime.",
  "She wrote a letter to her grandmother.",
  "The movie theater was almost empty.",
  "He repaired the bicycle by himself.",
  "We visited a castle in Europe.",
  "I listened to my favorite song on repeat.",
  "She made a handmade gift for her friend.",
  "The baby is learning to walk.",
  "He painted the walls of his room blue.",
  "We went to a concert last night.",
  "I love drinking coffee in the morning.",
  "She enjoys gardening in her free time.",
  "The dog chased the ball across the yard.",
  "He bought tickets for the football game.",
  "We went on a road trip last summer.",
  "I studied for the exam all night.",
  "She sang beautifully at the school recital.",
  "The weather is perfect for a picnic.",
  "He is learning how to play the piano.",
  "We watched the sunrise together.",
  "I took a photograph of the mountains.",
  "She cooked a delicious meal for her family.",
  "The cat jumped onto the table.",
  "He enjoys painting landscapes.",
  "We stayed at a cozy cabin in the woods.",
  "I read a fascinating article online.",
  "She wore a necklace her mother gave her.",
  "The children built a sandcastle on the beach.",
  "He fixed his car engine last weekend.",
  "We explored an old abandoned house.",
  "I listened to a podcast during my commute.",
  "She planted roses in the garden.",
  "The bird sang a beautiful song.",
  "He practiced yoga in the morning.",
  "We went skiing in the Alps.",
  "I bought a new pair of shoes.",
  "She likes to write poetry.",
  "The dog slept peacefully on the couch.",
  "He watched a documentary about space.",
  "We went fishing at the river.",
  "I organized my desk and cleaned the room.",
  "She painted a mural on the wall.",
  "The sun was shining brightly today.",
  "He enjoys playing basketball with friends.",
  "We had a barbecue in the backyard.",
  "I found a lost wallet on the street.",
  "She baked cookies for the school bake sale.",
  "The train ride was very scenic.",
  "He is studying for his final exams.",
  "We went camping in the forest.",
  "I love listening to jazz music.",
  "She decorated her room with fairy lights.",
  "The children enjoyed the puppet show.",
  "He repaired the leaking faucet.",
  "We went to a farmer's market on Sunday.",
  "I watched a documentary about wildlife.",
  "She bought fresh vegetables from the market.",
  "The dog ran around the park happily.",
  "He enjoys hiking in the mountains.",
  "We visited an art gallery yesterday.",
  "I wrote a short story for the competition.",
  "She learned to ride a bicycle.",
  "The sunset painted the sky orange.",
  "He played the violin beautifully.",
  "We attended a wedding last weekend.",
  "I cleaned the kitchen after cooking dinner.",
  "She organized a charity event.",
  "The baby smiled at her reflection in the mirror.",
  "He enjoys solving puzzles.",
  "We went to a music festival.",
  "I bought a new book yesterday.",
  "She went jogging in the park.",
  "The cat chased a butterfly in the garden.",
  "He painted his room green.",
  "We visited a zoo last Saturday.",
  "I drank a glass of fresh orange juice.",
  "She made a scrapbook of her travels.",
  "The children played hide and seek.",
  "He repaired the old wooden table.",
  "We went to a comedy show.",
  "I listened to an audiobook on the train.",
  "She planted tulips in the garden.",
  "The bird built a nest in the tree.",
  "He practiced his speech for the presentation.",
  "We went on a boat ride in the lake.",
  "I took pictures of the flowers in the garden.",
  "She sewed a dress for the party.",
  "The dog wagged its tail happily.",
  "He watched the stars through a telescope.",
  "We went to the mountains to see the snow.",
  "I wrote a poem for my friend.",
  "She baked a cake for the celebration.",
  "The children enjoyed the magic show.",
  "He fixed the broken window.",
  "We went to a botanical garden.",
  "I drank a cup of hot chocolate.",
  "She painted a picture of the sunset.",
  "The cat slept in a cozy corner.",
  "He enjoys running marathons.",
  "We went to a traditional festival.",
  "I listened to a classical music concert.",
  "She bought a new scarf for winter.",
  "The dog fetched the stick from the yard.",
  "He repaired the old bicycle.",
  "We explored the city on foot.",
  "I read an interesting novel.",
  "She wore a beautiful dress to the event.",
  "The children played with building blocks.",
  "He cooked a delicious dinner.",
  "We went to a historical museum.",
  "I listened to a podcast about history.",
  "She painted her bedroom walls.",
  "The dog barked at the passing car.",
  "He enjoys taking photographs.",
  "We went kayaking on the river.",
  "I wrote a letter to my pen pal.",
  "She planted sunflowers in the garden.",
  "The children laughed at the clown's tricks.",
  "He repaired the broken chair.",
  "We visited a medieval castle.",
  "I drank a cup of coffee at the café.",
  "She decorated the room with balloons.",
  "The cat chased a mouse in the house.",
  "He enjoys learning new languages.",
  "We went to a music concert.",
  "I read a magazine about travel.",
  "She wore a necklace from her grandmother.",
  "The children built a fort in the living room.",
  "He painted a landscape on canvas.",
  "We went hiking in the national park.",
  "I listened to my favorite playlist.",
  "She baked muffins for breakfast.",
  "The dog played with its toys.",
  "He repaired the bicycle chain.",
  "We went to a local art exhibition.",
  "I wrote a story about adventure.",
  "She planted flowers in pots.",
  "The children enjoyed the playground.",
  "He cooked breakfast for the family.",
  "We visited a historical monument.",
  "I drank a cup of green tea.",
  "She painted a picture of her cat.",
  "The cat slept on the bed.",
  "He enjoys playing the piano.",
  "We went to the countryside.",
  "I listened to an interesting lecture.",
  "She bought a new handbag.",
  "The children drew pictures with crayons.",
  "He fixed the broken lamp.",
  "We went to a music show.",
  "I read a book about science.",
  "She wore a beautiful bracelet.",
  "The dog ran around happily.",
  "He painted the fence white.",
  "We explored a nearby village.",
  "I wrote a poem about nature.",
  "She baked a pie for dessert.",
  "The children sang songs in the school choir.",
  "He repaired the old bookshelf.",
  "We went to a theme park.",
  "I listened to a new album.",
  "She planted a tree in the yard.",
  "The cat chased a toy mouse.",
  "He enjoys playing soccer.",
  "We went on a sightseeing tour.",
  "I read an interesting article.",
  "She wore a colorful dress.",
  "The children played in the garden.",
  "He fixed the car engine.",
  "We went to a zoo.",
  "I drank lemonade in the afternoon.",
  "She painted her room blue.",
  "The dog slept on the couch.",
  "He enjoys photography.",
  "We went to the beach.",
  "I listened to a podcast.",
  "She bought new shoes.",
  "The children laughed happily.",
  "He repaired the bicycle.",
  "We visited a museum.",
  "I wrote a short story.",
  "She planted flowers.",
  "The cat played with yarn.",
  "He cooked dinner.",
  "We went hiking.",
  "I read a novel.",
  "She wore a hat.",
  "The children played games.",
  "He fixed the chair.",
  "We went fishing.",
  "I listened to music.",
  "She baked bread.",
  "The dog ran fast.",
  "He painted a picture.",
  "We explored the forest.",
  "I wrote a letter.",
  "She bought a gift.",
  "The children drew pictures.",
  "He repaired the door.",
  "We went skiing.",
  "I drank coffee.",
  "She decorated the house.",
  "The cat climbed the tree.",
  "He enjoys reading.",
  "We visited a park.",
  "I listened to the radio.",
  "She made cookies.",
  "The dog barked loudly.",
  "He fixed the window.",
  "We went camping.",
  "I read a magazine.",
  "She painted a mural.",
  "The children played outside.",
  "He cooked breakfast.",
  "We went boating.",
  "I listened to a story.",
  "She bought a dress.",
  "The cat slept peacefully.",
  "He enjoys jogging.",
  "We explored the city.",
  "I wrote a poem.",
  "She baked a cake.",
  "The children sang songs.",
  "He repaired the fence.",
  "We went on a trip."
];